import { getDefaultAvatar } from '@/lib/utils'

// Helper functions to generate department-specific data

export const getEmergencyDepartmentData = (unit: string) => {
  const baseData = {
    'unit-a': {
      totalBeds: 12,
      occupiedBeds: 8,
      patients: [
        {
          id: '1',
          name: 'Rajesh Kumar',
          age: '58M',
          gender: 'M',
          avatar: getDefaultAvatar('Rajesh Kumar'),
          assignedDoctor: 'Dr. Sharma',
          uhi: '47362510',
          euhi: '0240122-0847',
          complaint: 'Chest Pain, Shortness of Breath',
          vitals: { hr: 112, bp: '165/95', spo2: 91 },
          vitalsSource: 'manual' as const,
          triageLevel: 1,
          triageLabel: 'Resuscitation',
          updatedBy: { name: 'Priya', avatar: getDefaultAvatar('Priya', 'nurse'), time: '2 minutes ago' },
          waitTime: '8 minutes',
          bed: 'ER-A1',
          arrivedAt: '19:20',
          vitalsHistory: [
            {
              id: 'v1',
              recordedBy: { name: 'Kavitha Nair', avatar: getDefaultAvatar('Kavitha Nair', 'nurse') },
              timestamp: '27 Jan, 18:28',
              source: 'ocr' as const,
              vitals: { hr: 109, bp: '165/95', spo2: 92, temp: 37.2, rr: 24 }
            },
            {
              id: 'v2',
              recordedBy: { name: 'Priya Sharma', avatar: getDefaultAvatar('Priya Sharma', 'nurse') },
              timestamp: '27 Jan, 18:43',
              source: 'ocr' as const,
              vitals: { hr: 107, bp: '165/95', spo2: 90, temp: 37.2, rr: 24 }
            }
          ],
          triageTimeline: [
            {
              id: 't1',
              to: 3,
              label: 'Urgent',
              reason: 'Initial triage assessment',
              performer: { name: 'Priya Sharma', avatar: getDefaultAvatar('Priya Sharma', 'nurse') },
              timestamp: '27 Jan, 18:28'
            },
            {
              id: 't2',
              from: 3,
              to: 1,
              label: 'Resuscitation',
              reason: 'Condition escalated',
              performer: { name: 'Priya Sharma', avatar: getDefaultAvatar('Priya Sharma', 'nurse') },
              timestamp: '27 Jan, 18:58'
            }
          ],
          nurseNotes: [
            {
              id: 'n1',
              category: 'Assessment' as const,
              note: 'Patient arrived. Initial assessment completed.',
              performer: { name: 'Priya Sharma', avatar: getDefaultAvatar('Priya Sharma', 'nurse') },
              timestamp: '27 Jan, 18:38'
            },
            {
              id: 'n2',
              category: 'Intervention' as const,
              note: 'IV established. Blood samples sent.',
              performer: { name: 'Anjali Reddy', avatar: getDefaultAvatar('Anjali Reddy', 'nurse') },
              timestamp: '27 Jan, 18:53'
            }
          ]
        },
        {
          id: '2',
          name: 'Meera Patel',
          age: '34F',
          gender: 'F',
          avatar: getDefaultAvatar('Meera Patel'),
          assignedDoctor: 'Dr. Reddy',
          uhi: '73829104',
          euhi: '0240122-0923',
          complaint: 'Severe Abdominal Pain',
          vitals: { hr: 98, bp: '130/85', spo2: 96 },
          vitalsSource: 'ocr' as const,
          triageLevel: 2,
          triageLabel: 'Emergency',
          updatedBy: { name: 'Ravi', avatar: getDefaultAvatar('Ravi', 'nurse'), time: '5 minutes ago' },
          waitTime: '15 minutes',
          bed: 'ER-A3',
          arrivedAt: '19:05',
          vitalsHistory: [
            {
              id: 'v1',
              recordedBy: { name: 'Ravi Kumar', avatar: getDefaultAvatar('Ravi Kumar', 'nurse') },
              timestamp: '27 Jan, 19:05',
              source: 'manual' as const,
              vitals: { hr: 98, bp: '130/85', spo2: 96, temp: 37.8, rr: 18 }
            },
            {
              id: 'v2',
              recordedBy: { name: 'Priya Sharma', avatar: getDefaultAvatar('Priya Sharma', 'nurse') },
              timestamp: '27 Jan, 19:15',
              source: 'ocr' as const,
              vitals: { hr: 95, bp: '128/82', spo2: 97, temp: 37.6, rr: 17 }
            }
          ],
          triageTimeline: [
            {
              id: 't1',
              to: 2,
              label: 'Emergency',
              reason: 'Initial triage - severe abdominal pain',
              performer: { name: 'Ravi Kumar', avatar: getDefaultAvatar('Ravi Kumar', 'nurse') },
              timestamp: '27 Jan, 19:05'
            }
          ],
          nurseNotes: [
            {
              id: 'n1',
              category: 'Assessment' as const,
              note: 'Patient complaining of severe abdominal pain. Pain scale 8/10.',
              performer: { name: 'Ravi Kumar', avatar: getDefaultAvatar('Ravi Kumar', 'nurse') },
              timestamp: '27 Jan, 19:07'
            },
            {
              id: 'n2',
              category: 'Intervention' as const,
              note: 'Pain medication administered. IV line established.',
              performer: { name: 'Anjali Reddy', avatar: getDefaultAvatar('Anjali Reddy', 'nurse') },
              timestamp: '27 Jan, 19:12'
            }
          ]
        },
        {
          id: '3',
          name: 'Amit Singh',
          age: '42M',
          gender: 'M',
          avatar: getDefaultAvatar('Amit Singh'),
          assignedDoctor: 'Dr. Kumar',
          uhi: '19283746',
          euhi: '0240122-0856',
          complaint: 'High Fever, Body Ache',
          vitals: { hr: 88, bp: '125/80', spo2: 97 },
          vitalsSource: 'manual' as const,
          triageLevel: 3,
          triageLabel: 'Urgent',
          updatedBy: { name: 'Kavitha', avatar: getDefaultAvatar('Kavitha', 'nurse'), time: '12 minutes ago' },
          waitTime: '32 minutes',
          bed: 'ER-A5',
          arrivedAt: '18:48',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
      ],
    },
    'unit-b': {
      totalBeds: 10,
      occupiedBeds: 6,
      patients: [
        {
          id: '4',
          name: 'Lakshmi Iyer',
          age: '67F',
          gender: 'F',
          avatar: getDefaultAvatar('Lakshmi Iyer'),
          assignedDoctor: 'Dr. Menon',
          uhi: '56473829',
          euhi: '0240122-1002',
          complaint: 'Breathing Difficulty, Wheezing',
          vitals: { hr: 102, bp: '145/92', spo2: 89 },
          vitalsSource: 'ocr' as const,
          triageLevel: 2,
          triageLabel: 'Emergency',
          updatedBy: { name: 'Suresh', avatar: getDefaultAvatar('Suresh', 'nurse'), time: '3 minutes ago' },
          waitTime: '11 minutes',
          bed: 'ER-B2',
          arrivedAt: '19:15',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
        {
          id: '5',
          name: 'Vikram Rao',
          age: '29M',
          gender: 'M',
          avatar: getDefaultAvatar('Vikram Rao'),
          assignedDoctor: 'Dr. Krishnan',
          uhi: '38475621',
          euhi: '0240122-1015',
          complaint: 'Road Accident, Multiple Injuries',
          vitals: { hr: 118, bp: '110/70', spo2: 94 },
          vitalsSource: 'manual' as const,
          triageLevel: 1,
          triageLabel: 'Resuscitation',
          updatedBy: { name: 'Anjali', avatar: getDefaultAvatar('Anjali', 'nurse'), time: '1 minute ago' },
          waitTime: '5 minutes',
          bed: 'ER-B1',
          arrivedAt: '19:21',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
      ],
    },
    'trauma': {
      totalBeds: 8,
      occupiedBeds: 5,
      patients: [
        {
          id: '6',
          name: 'Rahul Sharma',
          age: '25M',
          gender: 'M',
          avatar: getDefaultAvatar('Rahul Sharma'),
          assignedDoctor: 'Dr. Kapoor',
          uhi: '92847561',
          euhi: '0240122-1045',
          complaint: 'Fall from Height, Head Injury',
          vitals: { hr: 115, bp: '95/60', spo2: 92 },
          vitalsSource: 'ocr' as const,
          triageLevel: 1,
          triageLabel: 'Resuscitation',
          updatedBy: { name: 'Deepak', avatar: getDefaultAvatar('Deepak', 'nurse'), time: '4 minutes ago' },
          waitTime: '6 minutes',
          bed: 'TR-1',
          arrivedAt: '19:20',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
        {
          id: '7',
          name: 'Priya Nair',
          age: '31F',
          gender: 'F',
          avatar: getDefaultAvatar('Priya Nair'),
          assignedDoctor: 'Dr. Srinivasan',
          uhi: '74839201',
          euhi: '0240122-1052',
          complaint: 'Motor Vehicle Accident, Fracture',
          vitals: { hr: 105, bp: '120/78', spo2: 95 },
          vitalsSource: 'manual' as const,
          triageLevel: 2,
          triageLabel: 'Emergency',
          updatedBy: { name: 'Ramesh', avatar: getDefaultAvatar('Ramesh', 'nurse'), time: '7 minutes ago' },
          waitTime: '18 minutes',
          bed: 'TR-3',
          arrivedAt: '19:08',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
      ],
    },
    'care-unit': {
      totalBeds: 6,
      occupiedBeds: 3,
      patients: [
        {
          id: '8',
          name: 'Sunita Devi',
          age: '55F',
          gender: 'F',
          avatar: getDefaultAvatar('Sunita Devi'),
          assignedDoctor: 'Dr. Gupta',
          uhi: '65748392',
          euhi: '0240122-1110',
          complaint: 'Sudden Weakness, Dizziness',
          vitals: { hr: 92, bp: '140/88', spo2: 96 },
          vitalsSource: 'ocr' as const,
          triageLevel: 3,
          triageLabel: 'Urgent',
          updatedBy: { name: 'Sneha', avatar: getDefaultAvatar('Sneha', 'nurse'), time: '10 minutes ago' },
          waitTime: '25 minutes',
          bed: 'EC-2',
          arrivedAt: '19:01',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
        {
          id: '9',
          name: 'Karthik Reddy',
          age: '48M',
          gender: 'M',
          avatar: getDefaultAvatar('Karthik Reddy'),
          assignedDoctor: 'Dr. Rao',
          uhi: '47382910',
          euhi: '0240122-1118',
          complaint: 'Chest Discomfort, Palpitations',
          vitals: { hr: 108, bp: '155/90', spo2: 94 },
          vitalsSource: 'manual' as const,
          triageLevel: 2,
          triageLabel: 'Emergency',
          updatedBy: { name: 'Madhavi', avatar: getDefaultAvatar('Madhavi', 'nurse'), time: '6 minutes ago' },
          waitTime: '14 minutes',
          bed: 'EC-1',
          arrivedAt: '19:12',
          vitalsHistory: [],
          triageTimeline: [],
          nurseNotes: []
        },
      ],
    },
  }

  return baseData[unit as keyof typeof baseData] || baseData['unit-a']
}

export const getOPDData = (specialty: string) => {
  const baseData = {
    'general': {
      totalBeds: 20,
      occupiedBeds: 3,
      registeredCount: 3,
      patients: [
        {
          id: '1',
          initials: 'SM',
          name: 'Sanjay Mehta',
          age: '45M',
          avatar: getDefaultAvatar('Sanjay Mehta'),
          bloodGroup: 'B+',
          phone: '+91 98765 43210',
          uhi: '34567890',
          euhi: '0248122-0001',
          purpose: 'Follow-up Cardiology',
          doctor: 'Dr. Rajesh Verma',
          bed: 'OP-G-1',
          status: 'In Consultation' as const,
          statusColor: 'bg-green-100 text-green-700',
        },
        {
          id: '2',
          initials: 'KS',
          name: 'Kavita Sharma',
          age: '38F',
          avatar: getDefaultAvatar('Kavita Sharma'),
          bloodGroup: 'O+',
          phone: '+91 87654 32109',
          uhi: '45678901',
          euhi: '0248122-0002',
          purpose: 'General Checkup',
          doctor: 'Dr. Ananya Sharma',
          bed: 'OP-G-2',
          status: 'Waiting' as const,
          statusColor: 'bg-blue-100 text-blue-700',
        },
        {
          id: '3',
          initials: 'VR',
          name: 'Vikram Rao',
          age: '28M',
          avatar: getDefaultAvatar('Vikram Rao'),
          bloodGroup: 'A+',
          phone: '+91 76543 21098',
          uhi: '89012345',
          euhi: '0248122-0003',
          purpose: 'Post-ER Follow-up',
          doctor: 'Dr. Suresh Kumar',
          bed: 'OP-G-3',
          status: 'Waiting' as const,
          statusColor: 'bg-blue-100 text-blue-700',
          tags: ['ER Referral'],
        },
      ],
    },
    'cardiology': {
      totalBeds: 8,
      occupiedBeds: 4,
      registeredCount: 4,
      patients: [
        {
          id: '10',
          initials: 'RP',
          name: 'Ramesh Patel',
          age: '62M',
          avatar: getDefaultAvatar('Ramesh Patel'),
          bloodGroup: 'AB+',
          phone: '+91 98123 45678',
          uhi: '23456789',
          euhi: '0248122-0020',
          purpose: 'Heart Check-up',
          doctor: 'Dr. Rajesh Verma',
          bed: 'OP-C-1',
          status: 'In Consultation' as const,
          statusColor: 'bg-green-100 text-green-700',
        },
        {
          id: '11',
          initials: 'AN',
          name: 'Anita Nair',
          age: '56F',
          avatar: getDefaultAvatar('Anita Nair'),
          bloodGroup: 'B-',
          phone: '+91 87456 23109',
          uhi: '34567812',
          euhi: '0248122-0021',
          purpose: 'ECG Follow-up',
          doctor: 'Dr. Mohan Kumar',
          bed: 'OP-C-2',
          status: 'Waiting' as const,
          statusColor: 'bg-blue-100 text-blue-700',
        },
        {
          id: '12',
          initials: 'DG',
          name: 'Dinesh Gupta',
          age: '70M',
          avatar: getDefaultAvatar('Dinesh Gupta'),
          bloodGroup: 'O-',
          phone: '+91 76234 56789',
          uhi: '45678923',
          euhi: '0248122-0022',
          purpose: 'Post-Angioplasty Review',
          doctor: 'Dr. Rajesh Verma',
          bed: 'OP-C-3',
          status: 'In Consultation' as const,
          statusColor: 'bg-green-100 text-green-700',
          tags: ['Post-Surgery'],
        },
        {
          id: '13',
          initials: 'MS',
          name: 'Maya Srinivasan',
          age: '48F',
          avatar: getDefaultAvatar('Maya Srinivasan'),
          bloodGroup: 'A+',
          phone: '+91 98567 12345',
          uhi: '56789034',
          euhi: '0248122-0023',
          purpose: 'Chest Pain Assessment',
          doctor: 'Dr. Priya Reddy',
          bed: 'OP-C-4',
          status: 'Waiting' as const,
          statusColor: 'bg-blue-100 text-blue-700',
        },
      ],
    },
  }

  return baseData[specialty as keyof typeof baseData] || baseData['general']
}
